apiVersion: v1
kind: Pod
metadata:
  name: supra-test
spec:
  containers:
   - name: mavencontainer
     image: maven:3.5.4-jdk-8-slim
     command: ["sleep", "43200"]
   - name: kubectl
     image: bitnami/kubectl:latest
     command: ["sleep", "43200"]
   - name: docker
     image: docker:18.06.1
     command: ["tail", "-f", "/dev/null"]
     imagePullPolicy: Always
     volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
